timezone: Europe/Lisbon

starter:
  money: 25000
  spawner-type: skeleton
  spawner-amount: 1

daily:
  reward-points: 500

afk-zone:
  world: world
  corner-one: {x: 190, y: 68, z: 126}
  corner-two: {x: 198, y: 82, z: 118}

