container=chest
large=true
name=iregex:.*(auction|action ?house|1v1|2v2|help|helper|guide|sell|shop|point ?shop|spawner|kit|crate|rank|claim|tag|battle ?pass|daily|glory|tournament|duel|party|trade|market|reward|key|event|warp|home|profile|bounty|afk|menu).*
texture=plugin_menu_large.png
