# Creator rank LuckPerms fix

command /fixcreatorperms:
	permission: op
	trigger:
		send "&d&lMEDIA &8» &7A aplicar perms clipper..." to player
		execute console command "lp group clipper parent remove member"
		execute console command "lp group clipper parent remove warrior"
		execute console command "lp group clipper parent remove macer"
		execute console command "lp group clipper parent remove prime"
		execute console command "lp group clipper parent add knight"
		execute console command "lp group clipper permission unset skauction.listings.18"
		execute console command "lp group clipper permission unset skkeyall.multiplier.2"
		execute console command "lp group clipper permission unset skkeyall.bonus.creator"
		execute console command "lp group clipper permission set sksmp.homes.3 true"
		execute console command "lp group media parent remove warrior"
		execute console command "lp group media parent remove knight"
		execute console command "lp group media parent remove macer"
		execute console command "lp group media parent add prime"
		execute console command "lp group media parent add member"
		execute console command "lp group media permission unset skkeyall.bonus.creator"
		send "&d&lMEDIA &8» &aClipper=Knight perms. Media=Prime perks." to player
