#Minecraft server properties
#Tue Sep 08 14:16:47 CEST 2026
accepts-transfers=false
allow-flight=false
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
chat-spam-threshold-seconds=10
command-spam-threshold-seconds=10
debug=false
difficulty=normal
enable-code-of-conduct=false
enable-command-block=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=true
enable-status=true
enforce-secure-profile=true
enforce-whitelist=true
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=zcaVq7HY0xLm7iGLWi5Kb9XqO8eQ9Rx71gJLAZtU
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-build-height=256
max-chained-neighbor-updates=1000000
max-players=67
max-tick-time=60000
max-world-size=7500
motd=§e§lMerely§6§lMe §f§lS§7§lMP §8§l┃ §f§lE§7§lU\n▶ §a§lFIR§2§lST §a§lSEA§2§lSON §a§lNO§2§lW\!\!
network-compression-threshold=256
online-mode=true
op-permission-level=4
pause-when-empty-seconds=-1
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=27585
rate-limit=0
rcon.password=4zdvdRYh
rcon.port=27575
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=144.91.119.134
server-port=27585
simulation-distance=6
snooper-enabled=true
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=0
status-heartbeat-interval=0
sync-chunk-writes=true
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=8
white-list=false
