type=item
matchItems=minecraft:blaze_rod minecraft:mace minecraft:netherite_sword minecraft:diamond_sword minecraft:iron_sword minecraft:copper_sword minecraft:wooden_sword minecraft:stone_sword minecraft:golden_sword
texture=banhammer.png
model=banhammer.json
nbt.display.Name=iregex:.*ban ?hammer.*
